# Generated by Django 5.0.3 on 2024-03-16 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LayoutComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LayoutBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bodies', to='layouts.layout')),
                ('components', models.ManyToManyField(related_name='body_components', to='layouts.layoutcomponent')),
            ],
        ),
        migrations.CreateModel(
            name='LayoutFooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('components', models.ManyToManyField(related_name='footer_components', to='layouts.layoutcomponent')),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footers', to='layouts.layout')),
            ],
        ),
        migrations.CreateModel(
            name='LayoutHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('components', models.ManyToManyField(related_name='header_components', to='layouts.layoutcomponent')),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headers', to='layouts.layout')),
            ],
        ),
        migrations.CreateModel(
            name='LayoutSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting', models.JSONField()),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='layouts.layoutcomponent')),
            ],
        ),
        migrations.CreateModel(
            name='LayoutText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='layouts.layoutcomponent')),
            ],
        ),
    ]
