# Generated by Django 5.0.3 on 2024-03-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layouts', '0002_layoutcomponent_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='layout',
            name='type',
            field=models.CharField(default='layout1', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='layout',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
