# Generated by Django 5.0.3 on 2024-03-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layouts', '0003_layout_type_alter_layout_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='layout',
            name='style',
            field=models.CharField(default='style1', max_length=50),
            preserve_default=False,
        ),
    ]
