# Generated by Django 5.0.3 on 2024-03-16 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_accountlayout_layout'),
        ('layouts', '0004_layout_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='layout',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='layouts', to='accounts.accountlayout'),
            preserve_default=False,
        ),
    ]
