# Generated by Django 5.0.3 on 2024-03-10 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='firstname',
            field=models.CharField(default='Nathan', max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='lastname',
            field=models.CharField(default='McDonald', max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AccountImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='account_images')),
                ('Account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
