# Generated by Django 5.0.3 on 2024-03-10 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_firstname_account_lastname_accountimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountimage',
            old_name='Account',
            new_name='account',
        ),
    ]
