# Generated by Django 5.0.3 on 2024-03-10 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_account_accountimage_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='description',
            field=models.TextField(default='Coder', max_length=500, unique=True),
            preserve_default=False,
        ),
    ]
