# Generated by Django 5.0.3 on 2024-03-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_account_about_digitalproduct_physicalproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='about',
            field=models.TextField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='account',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='account',
            name='firstname',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='account',
            name='lastname',
            field=models.CharField(max_length=30),
        ),
    ]
