# Generated by Django 5.0.3 on 2024-03-13 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_account_about_alter_account_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountLayouts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('shop', 'Shop'), ('contact', 'Contact'), ('about', 'About')], max_length=10)),
                ('layout', models.JSONField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('account', 'page')},
            },
        ),
    ]
