# Generated by Django 5.0.3 on 2024-03-13 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_accountlayouts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccountLayouts',
            new_name='AccountLayout',
        ),
    ]
