# Generated by Django 5.0.3 on 2024-03-16 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rename_accountlayouts_accountlayout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountlayout',
            name='layout',
        ),
    ]
