# Generated by Django 5.0.3 on 2024-03-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_accountlayout_layout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountlayout',
            name='page',
            field=models.CharField(choices=[('home', 'Home'), ('shop', 'Shop'), ('contact', 'Contact'), ('about', 'About')], max_length=10),
        ),
    ]
